<?php

namespace AppBundle\Repository;

/**
 * DictionaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryRepository extends \Doctrine\ORM\EntityRepository
{
	public function findTopVoteUps($max)
	{
		return $this->_em
					->createQuery("SELECT d FROM ".$this->_entityName." d ORDER BY SIZE(d.voteUps) DESC")
					->setMaxResults($max)
					->getResult();
	}
	
	public function findFlopVoteDowns($max)
	{
		return $this->_em
					->createQuery("SELECT d FROM ".$this->_entityName." d ORDER BY SIZE(d.voteDowns) DESC")
					->setMaxResults($max)
					->getResult();
	}
}
