<?php

namespace AppBundle\Repository;

/**
 * lenouchiTermDefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lenouchiTermDefRepository extends \Doctrine\ORM\EntityRepository
{
}
