<?php

namespace AppBundle\Repository;

/**
 * VoteUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteUpRepository extends \Doctrine\ORM\EntityRepository
{
	
}
