<?php

namespace AppBundle\Repository;

/**
 * VoteDownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteDownRepository extends \Doctrine\ORM\EntityRepository
{
}
